apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
    name: https
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: traefik.seriousben.com
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      - name: acme-dns
        secret:
          secretName: acme-dns
      - name: acme
        persistentVolumeClaim:
          claimName: acme-pv
      containers:
      - image: traefik:1.3.5-alpine
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        env:
        - name: GCE_PROJECT
          value: projects-seriousben
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/acme-secret/service-account
        args:
        - --configfile=/config/traefik.toml
        - --web
        - --kubernetes
        #- --logLevel=DEBUG
        volumeMounts:
        - name: config
          readOnly: false
          mountPath: /config
        - name: acme
          readOnly: false
          mountPath: /acme
        - name: acme-dns
          readOnly: false
          mountPath: /secrets/acme-secret
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 0m
            memory: 10Mi
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
      [entryPoints.https.tls]
    [acme]
    email = "boudreau.benjamin@gmail.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    dnsProvider = "gcloud"
    acmeLogging = true
    onDemand = false
    onHostRule = true
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "seriousben.com"
    sans = ["www.seriousben.com", "traefik.seriousben.com"]
    [[acme.domains]]
    main = "video-boomerang.com"
    sans = ["www.video-boomerang.com", "api.video-boomerang.com"]
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acme-pv
  namespace: kube-system
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
