apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "base.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "base.fullname" . }}
data:
  acme-tls-issuer.yaml: |-
    apiVersion: certmanager.k8s.io/v1alpha1
    kind: Issuer
    metadata:
      labels:
        app: {{ template "base.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
      name: {{ template "base.fullname" . }}-acme-tls-issuer
    spec:
      acme:
        email: boudreau.benjamin@gmail.com
        #server: https://acme-staging.api.letsencrypt.org/directory
        server: https://acme-v01.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-issuer-key
        http01: {}
