apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "base.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "base.fullname" . }}-create-tls-issuer-job
spec:
  template:
    metadata:
      labels:
        app: {{ template "base.name" . }}
        release: {{ .Release.Name }}
      name: {{ template "base.fullname" . }}-create-tls-issuer
    spec:
      containers:
        - name: kube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.pullPolicy }}"
          command:
            - ./kubectl
            - apply
            - -f
            - /tmp/issuer-configmap/acme-tls-issuer.yaml
          volumeMounts:
            - mountPath: "/tmp/issuer-configmap"
              name: tmp-configmap-tls-issuer
      volumes:
        - name: tmp-configmap-tls-issuer
          configMap:
            name: {{ template "base.fullname" . }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "base.fullname" . }}-tls-issuer
