dependencies:
  - name: nginx-ingress
    version: 0.9.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: cert-manager
    version: 0.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: cert-manager.enabled
